-- +goose Up

-- ── 00001_init.sql ──────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS users (
    id                  BIGINT          PRIMARY KEY,
    telegram_id         BIGINT,
    dob			        DATE,
    name                TEXT,
    gender              BOOLEAN,
    created_at          TIMESTAMPTZ		NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ		NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS measurements (
    id          		BIGINT		    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id	            BIGINT,
    height				INT,
    weight				NUMERIC(5,2),
    bust_size           INT             NOT NULL DEFAULT 0,
	waist_size          INT             NOT NULL DEFAULT 0,
	hip_size            INT             NOT NULL DEFAULT 0,
    activity_type		TEXT            CHECK (activity_type IN ('sedentary','light','moderate','high','extreme')),
    goal                TEXT            CHECK (goal IN ('lose','maintain','gain')),
    created_at			TIMESTAMPTZ		NOT NULL DEFAULT now()
);

CREATE TYPE macroses AS (
    fiber               NUMERIC(5,2),
    fat                 NUMERIC(5,2),
    carbohydrates       NUMERIC(5,2)
);

CREATE INDEX measurements_user_created_idx ON measurements (user_id, created_at DESC);
